name: papproject
description: "Dps coloco"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  provider: ^6.1.2
  image_picker: ^1.1.2
  html: ^0.15.4


  google_maps_flutter: ^2.6.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5


  flutterfire_cli: ^0.1.1+2
  flutter_config: ^2.0.2
  fluttertoast: ^8.2.5
  flutter_polyline_points: ^2.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/wave.json
    - assets/back_ground.png
    - assets/map_style.json
    - assets/routes.json
    - assets/stopBus.png
